theme = "monokai_MS"
# theme = "monokai"
# theme = "molokai_MS"

[editor]
line-number = "relative"
cursorline = true
lsp.display-inlay-hints = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[keys.insert]
C-c = "normal_mode" # Maps Ctrl-C to exit insert mode

[keys.insert.j]
j = "normal_mode" # Maps `jj` to exit insert mode
k = "normal_mode" # Maps `jk` to exit insert mode

[keys.insert.","]
"." = "normal_mode" # Maps ',.' to exit insert mode

[keys.normal]
C-s = ":write" # Ctrl and 's' to write
Cmd-s = ":write" # Cmd or Win or Meta and 's' to write
"ret" = "goto_word"
"0" = "goto_line_start" 
"$" = "goto_line_end"
"G" = "goto_last_line"
# Para que es mueva por lineas completas y no lineas visuales e wordwarp mode
j = "move_line_down"
k = "move_line_up"
A-z = ":toggle soft-wrap.enable" # Para cambiar el word wrap
A-l = ":toggle line-number relative absolute" # Para cambiar los numeros de linea de relativos a absolutos
"V" = ["extend_line_below", "select_mode"] # Simula la V de vim, selecciona la linea actual y se queda en modo selecion

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
v = ":vsplit"
z = ":toggle soft-wrap.enable" # Para cambiar el word wrap
l = ":toggle line-number relative absolute" # Para cambiar los numeros de linea de relativos a absolutos
s = ":write"
q = ":quit"
"-" = ":toggle auto-save.after-delay.enable"

[keys.normal."g"]
G = "goto_last_line"
# Gestion de mayusculas y minúsculas
# Recordemos que ~ cambia de uppercase a lowercase y vicersa
u = "switch_to_lowercase" # Simulamos gu de vim
U = "switch_to_uppercase" # Simulamos gU de vim

# Mejora de la statusline - powerline
[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]









